# Dockerfile
FROM horovod/horovod:0.20.0-tf2.3.0-torch1.6.0-mxnet1.6.0.post0-py3.7-cuda10.1

# Get example python scripts
COPY tensorflow2_mnist_elastic.py /examples/elastic/tensorflow2_mnist_elastic.py
