apiVersion: kubeflow.org/v1
kind: MPIJob
metadata:
  name: pytorch-mnist-elastic
  namespace: my-ns
spec:
  slotsPerWorker: 1
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: sincerityhun/horovod:0.20.0-tf2.3.0-torch1.6.0-mxnet1.6.0.post0-py3.7-cuda10.1-ver2
            name: mpi-launcher
            imagePullPolicy: Always
            command:
            - horovodrun
            args:
            - -np
            - "2"
            - --min-np
            - "1"
            - --max-np
            - "3"
            - --host-discovery-script
            - /etc/mpi/discover_hosts.sh
            - python
            - /examples/elastic/sincerityhun_pytorch_mnist_elastic.py
            - --batch-size
            - "64"
            - --epochs
            - "10000"
            - --log_interval_for_monitor
            - "10"
            resources:
              limits:
                cpu: 1
                memory: "8Gi"
                nvidia.com/gpu: 1
            volumeMounts:
            - name: log-volume
              mountPath: /examples/elastic
          volumes:
          - name: log-volume
            persistentVolumeClaim:
              claimName: mpi-logs
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - image: sincerityhun/horovod:0.20.0-tf2.3.0-torch1.6.0-mxnet1.6.0.post0-py3.7-cuda10.1-ver2
            name: mpi-worker
            resources:
              limits:
                cpu: 2
                memory: "16Gi"
                nvidia.com/gpu: 1
            volumeMounts:
            - name: log-volume
              mountPath: /examples/elastic
          volumes:
          - name: log-volume
            persistentVolumeClaim:
              claimName: mpi-logs